[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
erc4626_token = "ZtmCJQpJFxDKJ2g6tU8LrJeqgRNm8NjFyUnHgWjnzuD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/sotatek/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
